log:
  name: java

spring:
  main:
    allow-circular-references: true
  application:
    name: jmJava
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.59.4:3306/dev?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: zxcvbnm110.
            
server:
  port: 8080
  servlet:
    context-path: /
            